/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TechRouteImport } from './routes/tech'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as OakvilleRouteImport } from './routes/oakville'
import { Route as MississaugaRouteImport } from './routes/mississauga'
import { Route as MiltonRouteImport } from './routes/milton'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BookRouteImport } from './routes/book'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as AppVisitsRouteImport } from './routes/app.visits'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppHealthRouteImport } from './routes/app.health'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AdminWalkthroughsRouteImport } from './routes/admin.walkthroughs'
import { Route as AdminVisitsRouteImport } from './routes/admin.visits'
import { Route as AdminTechniciansRouteImport } from './routes/admin.technicians'
import { Route as AdminSubscribersRouteImport } from './routes/admin.subscribers'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRoutesRouteImport } from './routes/admin.routes'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminMetricsRouteImport } from './routes/admin.metrics'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'
import { Route as AppVisitsIdRouteImport } from './routes/app.visits.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TechRoute = TechRouteImport.update({
  id: '/tech',
  path: '/tech',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const OakvilleRoute = OakvilleRouteImport.update({
  id: '/oakville',
  path: '/oakville',
  getParentRoute: () => rootRouteImport,
} as any)
const MississaugaRoute = MississaugaRouteImport.update({
  id: '/mississauga',
  path: '/mississauga',
  getParentRoute: () => rootRouteImport,
} as any)
const MiltonRoute = MiltonRouteImport.update({
  id: '/milton',
  path: '/milton',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVisitsRoute = AppVisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthRoute = AppHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AdminWalkthroughsRoute = AdminWalkthroughsRouteImport.update({
  id: '/walkthroughs',
  path: '/walkthroughs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVisitsRoute = AdminVisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTechniciansRoute = AdminTechniciansRouteImport.update({
  id: '/technicians',
  path: '/technicians',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoutesRoute = AdminRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMetricsRoute = AdminMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRoute,
} as any)
const AppVisitsIdRoute = AppVisitsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppVisitsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/book': typeof BookRoute
  '/checkout': typeof CheckoutRoute
  '/design-system': typeof DesignSystemRoute
  '/milton': typeof MiltonRoute
  '/mississauga': typeof MississaugaRoute
  '/oakville': typeof OakvilleRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/signin': typeof SigninRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tech': typeof TechRoute
  '/terms': typeof TermsRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/metrics': typeof AdminMetricsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/routes': typeof AdminRoutesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/technicians': typeof AdminTechniciansRoute
  '/admin/visits': typeof AdminVisitsRoute
  '/admin/walkthroughs': typeof AdminWalkthroughsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/health': typeof AppHealthRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/visits': typeof AppVisitsRouteWithChildren
  '/learn/$slug': typeof LearnSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/visits/$id': typeof AppVisitsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/book': typeof BookRoute
  '/checkout': typeof CheckoutRoute
  '/design-system': typeof DesignSystemRoute
  '/milton': typeof MiltonRoute
  '/mississauga': typeof MississaugaRoute
  '/oakville': typeof OakvilleRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/signin': typeof SigninRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tech': typeof TechRoute
  '/terms': typeof TermsRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/metrics': typeof AdminMetricsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/routes': typeof AdminRoutesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/technicians': typeof AdminTechniciansRoute
  '/admin/visits': typeof AdminVisitsRoute
  '/admin/walkthroughs': typeof AdminWalkthroughsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/health': typeof AppHealthRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/visits': typeof AppVisitsRouteWithChildren
  '/learn/$slug': typeof LearnSlugRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/app/visits/$id': typeof AppVisitsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/book': typeof BookRoute
  '/checkout': typeof CheckoutRoute
  '/design-system': typeof DesignSystemRoute
  '/milton': typeof MiltonRoute
  '/mississauga': typeof MississaugaRoute
  '/oakville': typeof OakvilleRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/signin': typeof SigninRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tech': typeof TechRoute
  '/terms': typeof TermsRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/metrics': typeof AdminMetricsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/routes': typeof AdminRoutesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/technicians': typeof AdminTechniciansRoute
  '/admin/visits': typeof AdminVisitsRoute
  '/admin/walkthroughs': typeof AdminWalkthroughsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/health': typeof AppHealthRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/visits': typeof AppVisitsRouteWithChildren
  '/learn/$slug': typeof LearnSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/visits/$id': typeof AppVisitsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/admin'
    | '/app'
    | '/book'
    | '/checkout'
    | '/design-system'
    | '/milton'
    | '/mississauga'
    | '/oakville'
    | '/plans'
    | '/privacy'
    | '/signin'
    | '/sitemap.xml'
    | '/tech'
    | '/terms'
    | '/admin/catalog'
    | '/admin/leads'
    | '/admin/metrics'
    | '/admin/plans'
    | '/admin/routes'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/admin/technicians'
    | '/admin/visits'
    | '/admin/walkthroughs'
    | '/app/billing'
    | '/app/health'
    | '/app/reports'
    | '/app/settings'
    | '/app/visits'
    | '/learn/$slug'
    | '/admin/'
    | '/app/'
    | '/app/visits/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate'
    | '/book'
    | '/checkout'
    | '/design-system'
    | '/milton'
    | '/mississauga'
    | '/oakville'
    | '/plans'
    | '/privacy'
    | '/signin'
    | '/sitemap.xml'
    | '/tech'
    | '/terms'
    | '/admin/catalog'
    | '/admin/leads'
    | '/admin/metrics'
    | '/admin/plans'
    | '/admin/routes'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/admin/technicians'
    | '/admin/visits'
    | '/admin/walkthroughs'
    | '/app/billing'
    | '/app/health'
    | '/app/reports'
    | '/app/settings'
    | '/app/visits'
    | '/learn/$slug'
    | '/admin'
    | '/app'
    | '/app/visits/$id'
  id:
    | '__root__'
    | '/'
    | '/activate'
    | '/admin'
    | '/app'
    | '/book'
    | '/checkout'
    | '/design-system'
    | '/milton'
    | '/mississauga'
    | '/oakville'
    | '/plans'
    | '/privacy'
    | '/signin'
    | '/sitemap.xml'
    | '/tech'
    | '/terms'
    | '/admin/catalog'
    | '/admin/leads'
    | '/admin/metrics'
    | '/admin/plans'
    | '/admin/routes'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/admin/technicians'
    | '/admin/visits'
    | '/admin/walkthroughs'
    | '/app/billing'
    | '/app/health'
    | '/app/reports'
    | '/app/settings'
    | '/app/visits'
    | '/learn/$slug'
    | '/admin/'
    | '/app/'
    | '/app/visits/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivateRoute: typeof ActivateRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  BookRoute: typeof BookRoute
  CheckoutRoute: typeof CheckoutRoute
  DesignSystemRoute: typeof DesignSystemRoute
  MiltonRoute: typeof MiltonRoute
  MississaugaRoute: typeof MississaugaRoute
  OakvilleRoute: typeof OakvilleRoute
  PlansRoute: typeof PlansRoute
  PrivacyRoute: typeof PrivacyRoute
  SigninRoute: typeof SigninRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TechRoute: typeof TechRoute
  TermsRoute: typeof TermsRoute
  LearnSlugRoute: typeof LearnSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech': {
      id: '/tech'
      path: '/tech'
      fullPath: '/tech'
      preLoaderRoute: typeof TechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oakville': {
      id: '/oakville'
      path: '/oakville'
      fullPath: '/oakville'
      preLoaderRoute: typeof OakvilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mississauga': {
      id: '/mississauga'
      path: '/mississauga'
      fullPath: '/mississauga'
      preLoaderRoute: typeof MississaugaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milton': {
      id: '/milton'
      path: '/milton'
      fullPath: '/milton'
      preLoaderRoute: typeof MiltonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/visits': {
      id: '/app/visits'
      path: '/visits'
      fullPath: '/app/visits'
      preLoaderRoute: typeof AppVisitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/health': {
      id: '/app/health'
      path: '/health'
      fullPath: '/app/health'
      preLoaderRoute: typeof AppHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/walkthroughs': {
      id: '/admin/walkthroughs'
      path: '/walkthroughs'
      fullPath: '/admin/walkthroughs'
      preLoaderRoute: typeof AdminWalkthroughsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/visits': {
      id: '/admin/visits'
      path: '/visits'
      fullPath: '/admin/visits'
      preLoaderRoute: typeof AdminVisitsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/technicians': {
      id: '/admin/technicians'
      path: '/technicians'
      fullPath: '/admin/technicians'
      preLoaderRoute: typeof AdminTechniciansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscribers': {
      id: '/admin/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/routes': {
      id: '/admin/routes'
      path: '/routes'
      fullPath: '/admin/routes'
      preLoaderRoute: typeof AdminRoutesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/metrics': {
      id: '/admin/metrics'
      path: '/metrics'
      fullPath: '/admin/metrics'
      preLoaderRoute: typeof AdminMetricsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/visits/$id': {
      id: '/app/visits/$id'
      path: '/$id'
      fullPath: '/app/visits/$id'
      preLoaderRoute: typeof AppVisitsIdRouteImport
      parentRoute: typeof AppVisitsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminMetricsRoute: typeof AdminMetricsRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminRoutesRoute: typeof AdminRoutesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
  AdminTechniciansRoute: typeof AdminTechniciansRoute
  AdminVisitsRoute: typeof AdminVisitsRoute
  AdminWalkthroughsRoute: typeof AdminWalkthroughsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCatalogRoute: AdminCatalogRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminMetricsRoute: AdminMetricsRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminRoutesRoute: AdminRoutesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
  AdminTechniciansRoute: AdminTechniciansRoute,
  AdminVisitsRoute: AdminVisitsRoute,
  AdminWalkthroughsRoute: AdminWalkthroughsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppVisitsRouteChildren {
  AppVisitsIdRoute: typeof AppVisitsIdRoute
}

const AppVisitsRouteChildren: AppVisitsRouteChildren = {
  AppVisitsIdRoute: AppVisitsIdRoute,
}

const AppVisitsRouteWithChildren = AppVisitsRoute._addFileChildren(
  AppVisitsRouteChildren,
)

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppHealthRoute: typeof AppHealthRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppVisitsRoute: typeof AppVisitsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppHealthRoute: AppHealthRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppVisitsRoute: AppVisitsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivateRoute: ActivateRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  BookRoute: BookRoute,
  CheckoutRoute: CheckoutRoute,
  DesignSystemRoute: DesignSystemRoute,
  MiltonRoute: MiltonRoute,
  MississaugaRoute: MississaugaRoute,
  OakvilleRoute: OakvilleRoute,
  PlansRoute: PlansRoute,
  PrivacyRoute: PrivacyRoute,
  SigninRoute: SigninRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TechRoute: TechRoute,
  TermsRoute: TermsRoute,
  LearnSlugRoute: LearnSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
